name: CD - Producción Continua (Delivery)

on:
  workflow_dispatch:  #Ejecucción manual
    inputs:
        environment:
          description: 'Selecciona el entorno (prod)'
          required: true
          default: 'prod'
          type: choice
          options:
          - prod

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    environment: produccion #Entorno
    
    steps:

      - name: Checkout del código   #Clonación del repo
        uses: actions/checkout@v2

      - name: Simular hackaton CLI  #Simulación Hackaton CLI
        run: | 
          echo -e '#!/bin/bash\necho "[SIMULACIÓN] hackaton \$@"' | sudo tee /usr/local/bin/hackaton
          sudo chmod +x /usr/local/bin/hackaton

      - name: Instalar dependencias necesarias #Configuración dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx ufw curl jq
      
      - name: Configurar cortafuegos  #Configuración Firewall
        run: |
          sudo ufw allow OpenSSH
          sudo ufw allow 'Nginx Full'
          sudo ufw --force enable
          sudo ufw status  

      - name: Configurar NGINX (dev)
        if: ${{ github.event.inputs.environment == 'prod' }}  # Solo para entorno dev
        run: |
            echo "server {
              listen 80;
              server_name mi-app-dev.com;
              location / {
                proxy_pass http://localhost:3001;
              }
            }" | sudo tee /etc/nginx/sites-available/prod
            sudo ln -s /etc/nginx/sites-available/prod /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
      
      - name: Desplegar en desarrollo
    
        env:
          DB_USER: ${{ github.action.secrets.DB_USER_PROD}}
          DB_PASS: ${{ github.action.secrets.DB_PASS_PROD}}
          API_KEY: ${{ github.action.secrets.API_KEY_PROD}}
        run: |
          echo "Entorno: PROD"
          hackaton deploy --env=prod
          hackaton restart app --env=prod
          curl -I http://localhost

      - name: Valores
        run: |
          echo "DB_USER_PROD: ${{ github.action.secrets.DB_USER_PROD }}"
          echo "DB_PASS_PROD: ${{ github.action.secrets.DB_PASS_PROD }}"
          echo "API_KEY_PROD: ${{ github.action.secrets.API_KEY_PROD }}"